# Anaconda env file
# Use as: conda env create -f environment.yml
# Then activate as : conda activate ml4sci
name: ml4sci
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - anaconda
  - pip
  - pip:
    - -r requirements.txt
